### ISSUE TITLE
Django tests have data persisting across tests

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach-django#11] opened 2019-10-08 15:07 UTC
It seems like the current client does not clean up the database correctly in between tests, leading to tests that assert output equality of different queries to fail.

Reproduction:

Using the django test suite -- 

```
./runtests.py postgres_tests.test_array.TestSaveLoad.test_tuples --parallel 1
```
succeeds, while running the entire test class.
```
./runtests.py postgres_tests.test_array.TestSaveLoad --parallel 1
```
fails. With more inspection, you can see that the IntegerArrayModel's table has rows in it at the beginning of the test when running the full test class.

**Comment by timgraham** [comment] 2019-11-08 14:43
It doesn't seem like an issue in Django because I can't reproduce this testing with PostgreSQL. We're not going to try to support the `postgres_tests` (which are for `django.contrib.postgres`) at this time so I'm going to close this.

**Closed by timgraham** 2019-11-08 14:43 UTC
